# Generated by Django 6.0.2 on 2026-02-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '2. Compañías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Regimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='75th Ranger Regiment', help_text='La unidad madre.', max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Regimientos',
            },
        ),
        migrations.CreateModel(
            name='Escuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuadras', to='orbat.compania')),
            ],
            options={
                'verbose_name_plural': '3. Escuadras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_milsim', models.CharField(max_length=100)),
                ('rango', models.CharField(choices=[('JIP', 'JIP (Just In Process)'), ('PV1', 'PV1 - Private'), ('PV2', 'PV2 - Private Second Class'), ('PFC', 'PFC - Private First Class'), ('CPL', 'CPL - Corporal'), ('SGT', 'SGT - Sergeant'), ('SSG', 'SSG - Staff Sergeant'), ('SFC', 'SFC - Sergeant First Class'), ('MSG', 'MSG - Master Sergeant'), ('1SG', '1SG - First Sergeant'), ('SGM', 'SGM - Sergeant Major'), ('CSM', 'CSM - Command Sergeant Major'), ('WO1', 'WO1 - Warrant Officer 1'), ('CW2', 'CW2 - Chief Warrant Officer 2'), ('CW3', 'CW3 - Chief Warrant Officer 3'), ('CW4', 'CW4 - Chief Warrant Officer 4'), ('CW5', 'CW5 - Chief Warrant Officer 5'), ('2LT', '2LT - Second Lieutenant'), ('1LT', '1LT - First Lieutenant'), ('CPT', 'CPT - Captain'), ('MAJ', 'MAJ - Major'), ('LTC', 'LTC - Lieutenant Colonel'), ('COL', 'COL - Colonel')], default='JIP', max_length=5)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('escuadra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='orbat.escuadra')),
            ],
            options={
                'verbose_name_plural': '4. Miembros',
                'ordering': ['-rango', 'nombre_milsim'],
            },
        ),
        migrations.AddField(
            model_name='compania',
            name='regimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companias', to='orbat.regimiento'),
        ),
    ]
