# Generated by Django 6.0.2 on 2026-02-12 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Alpha Company', max_length=100)),
                ('logo', models.CharField(blank=True, help_text='URL del escudo de la compañía', max_length=200)),
            ],
            options={
                'verbose_name': '2. Compañía',
                'verbose_name_plural': '2. Compañías',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Escuadra 1-1', max_length=100)),
                ('indicativo_radio', models.CharField(blank=True, help_text='Ej: Viking 1-1', max_length=50)),
            ],
            options={
                'verbose_name': '4. Escuadra',
                'verbose_name_plural': '4. Escuadras',
            },
        ),
        migrations.CreateModel(
            name='Regimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='75th Ranger Regiment', max_length=100)),
                ('descripcion', models.TextField(blank=True, verbose_name='Misión / Historia')),
            ],
            options={
                'verbose_name': '1. Regimiento',
                'verbose_name_plural': '1. Regimientos',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_milsim', models.CharField(max_length=100, verbose_name='Nick')),
                ('rango', models.CharField(choices=[('COL', 'Coronel (COL)'), ('LTC', 'Teniente Coronel (LTC)'), ('MAJ', 'Mayor (MAJ)'), ('CPT', 'Capitán (CPT)'), ('1LT', 'Teniente Primero (1LT)'), ('2LT', 'Teniente Segundo (2LT)'), ('CW5', 'Chief Warrant Officer 5'), ('CW4', 'Chief Warrant Officer 4'), ('WO1', 'Warrant Officer 1'), ('CSM', 'Sargento Mayor de Comando (CSM)'), ('1SG', 'Sargento Primero (1SG)'), ('SFC', 'Sargento de Primera Clase (SFC)'), ('SSG', 'Sargento de Estado Mayor (SSG)'), ('SGT', 'Sargento (SGT)'), ('CPL', 'Cabo (CPL)'), ('SPC', 'Especialista (SPC)'), ('PFC', 'Soldado de Primera (PFC)'), ('PV2', 'Soldado (PV2)'), ('PV1', 'Recluta (PV1)')], default='PV1', max_length=5)),
                ('rol', models.CharField(default='Fusilero', help_text='Ej: Líder de Escuadra, Médico, Ametrallador', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('discord_id', models.CharField(blank=True, max_length=50)),
                ('steam_id', models.CharField(blank=True, max_length=50)),
                ('cursos', models.ManyToManyField(blank=True, to='orbat.curso')),
                ('escuadra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbat.escuadra', verbose_name='Unidad Asignada')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': '5. Personal',
                'ordering': ['-rango', 'nombre_milsim'],
            },
        ),
        migrations.CreateModel(
            name='Peloton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 1er Pelotón (Strike) o Mando de Compañía (HQ)', max_length=100)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelotones', to='orbat.compania')),
            ],
            options={
                'verbose_name': '3. Pelotón / Sección',
                'verbose_name_plural': '3. Pelotones',
            },
        ),
        migrations.AddField(
            model_name='escuadra',
            name='peloton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuadras', to='orbat.peloton'),
        ),
        migrations.AddField(
            model_name='compania',
            name='regimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companias', to='orbat.regimiento'),
        ),
    ]
