# Generated by Django 6.0.2 on 2026-02-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Curso / Especialidad',
                'verbose_name_plural': 'Instrucción: Cursos',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fase de Instrucción',
                'verbose_name_plural': 'Instrucción: Fases',
            },
        ),
        migrations.AlterModelOptions(
            name='compania',
            options={},
        ),
        migrations.AlterModelOptions(
            name='escuadra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regimiento',
            options={'verbose_name': 'Sede del Mando', 'verbose_name_plural': '1. Mando Central'},
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='fecha_ingreso',
        ),
        migrations.AlterField(
            model_name='compania',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compania',
            name='regimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbat.regimiento'),
        ),
        migrations.AlterField(
            model_name='escuadra',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbat.compania'),
        ),
        migrations.AlterField(
            model_name='escuadra',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='escuadra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orbat.escuadra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rango',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='regimiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='orbat.curso', verbose_name='Cursos Completados'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='orbat.fase'),
        ),
    ]
