# Generated by Django 6.0.2 on 2026-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peloton',
            options={'verbose_name': '3. Pelotón', 'verbose_name_plural': '3. Pelotones'},
        ),
        migrations.AddField(
            model_name='regimiento',
            name='comandante',
            field=models.CharField(blank=True, help_text='Nombre del CO del Regimiento', max_length=100),
        ),
        migrations.AlterField(
            model_name='compania',
            name='logo',
            field=models.CharField(blank=True, help_text='URL del escudo', max_length=200),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rango',
            field=models.CharField(choices=[('COL', 'Coronel (COL)'), ('LTC', 'Teniente Coronel (LTC)'), ('MAJ', 'Mayor (MAJ)'), ('CPT', 'Capitán (CPT)'), ('LT1', 'Teniente Primero (1LT)'), ('LT2', 'Teniente Segundo (2LT)'), ('CW5', 'Chief Warrant Officer 5'), ('CW4', 'Chief Warrant Officer 4'), ('WO1', 'Warrant Officer 1'), ('CSM', 'Sargento Mayor de Comando (CSM)'), ('SG1', 'Sargento Primero (1SG)'), ('SFC', 'Sargento de Primera Clase (SFC)'), ('SSG', 'Sargento de Estado Mayor (SSG)'), ('SGT', 'Sargento (SGT)'), ('CPL', 'Cabo (CPL)'), ('SPC', 'Especialista (SPC)'), ('PFC', 'Soldado de Primera (PFC)'), ('PV2', 'Soldado (PV2)'), ('PV1', 'Recluta (PV1)')], default='PV1', max_length=5),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rol',
            field=models.CharField(default='Fusilero', max_length=100),
        ),
        migrations.AlterField(
            model_name='peloton',
            name='nombre',
            field=models.CharField(help_text='Ej: 1er Pelotón', max_length=100),
        ),
    ]
