# Generated by Django 6.0.2 on 2026-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0002_curso_fase_alter_compania_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compania',
            options={'verbose_name': 'Compañía', 'verbose_name_plural': '2. Compañías'},
        ),
        migrations.AlterModelOptions(
            name='escuadra',
            options={'verbose_name': 'Escuadra', 'verbose_name_plural': '3. Escuadras'},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'verbose_name': 'Soldado', 'verbose_name_plural': '4. Personal'},
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='orbat.curso'),
        ),
        migrations.AlterField(
            model_name='regimiento',
            name='nombre',
            field=models.CharField(default='75th Ranger RGT', max_length=100),
        ),
    ]
