# Generated by Django 6.0.2 on 2026-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0002_alter_peloton_options_regimiento_comandante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='notas_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Administración'),
        ),
    ]
