# Generated by Django 6.0.2 on 2026-02-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0003_miembro_notas_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbat.compania'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='peloton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbat.peloton'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='regimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbat.regimiento'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='escuadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbat.escuadra'),
        ),
    ]
