# Generated by GitHub Copilot on 2026-02-13

from django.db import migrations, models


def forward_update_abbreviations(apps, schema_editor):
    Miembro = apps.get_model('orbat', 'Miembro')
    mapping = {
        'LT1': '1LT',
        'LT2': '2LT',
        'SG1': '1SG',
    }
    for old, new in mapping.items():
        Miembro.objects.filter(rango=old).update(rango=new)


def backward_restore_abbreviations(apps, schema_editor):
    Miembro = apps.get_model('orbat', 'Miembro')
    mapping = {
        '1LT': 'LT1',
        '2LT': 'LT2',
        '1SG': 'SG1',
    }
    for old, new in mapping.items():
        Miembro.objects.filter(rango=old).update(rango=new)


class Migration(migrations.Migration):

    dependencies = [
        ('orbat', '0004_miembro_compania_miembro_peloton_miembro_regimiento_and_more'),
    ]

    operations = [
        # Update field choices to reflect new TextChoices in models
        migrations.AlterField(
            model_name='miembro',
            name='rango',
            field=models.CharField(
                max_length=5,
                default='PV1',
                choices=[
                    ('COL', 'Coronel (COL)'),
                    ('LTC', 'Teniente Coronel (LTC)'),
                    ('MAJ', 'Mayor (MAJ)'),
                    ('CPT', 'Capitán (CPT)'),
                    ('1LT', 'Teniente Primero (1LT)'),
                    ('2LT', 'Teniente Segundo (2LT)'),
                    ('CW5', 'Chief Warrant Officer 5'),
                    ('CW4', 'Chief Warrant Officer 4'),
                    ('CW3', 'Chief Warrant Officer 3'),
                    ('CW2', 'Chief Warrant Officer 2'),
                    ('WO1', 'Warrant Officer 1'),
                    ('CSM', 'Sargento Mayor de Comando (CSM)'),
                    ('SGM', 'Sargento Mayor (SGM)'),
                    ('1SG', 'Sargento Primero (1SG)'),
                    ('MSG', 'Sargento Maestro (MSG)'),
                    ('SFC', 'Sargento de Primera Clase (SFC)'),
                    ('SSG', 'Sargento de Estado Mayor (SSG)'),
                    ('SGT', 'Sargento (SGT)'),
                    ('CPL', 'Cabo (CPL)'),
                    ('SPC', 'Especialista (SPC)'),
                    ('PFC', 'Soldado de Primera (PFC)'),
                    ('PV2', 'Soldado (PV2)'),
                    ('PV1', 'Recluta (PV1)'),
                ],
            ),
        ),
        migrations.RunPython(forward_update_abbreviations, backward_restore_abbreviations),
    ]
