"""
Django settings for gestion_milsim project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0m0xd8lkbv!t0vyfl2abj0z1fg77k60!orcy&8ra$g^g81-jz%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 1. El comodín para las visitas
ALLOWED_HOSTS = ['*']

# 2. El comodín para la seguridad del formulario (CSRF)
# Usamos el asterisco real (*) para autorizar todos los links de ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app'
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',                      # <--- Jazzmin siempre primero
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orbat',                        # Tu aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_milsim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_milsim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# --- CAMBIO: Configuración regional para Latam ---
LANGUAGE_CODE = 'es-cl'      # Español de Chile

TIME_ZONE = 'America/Santiago' # Hora de Chile

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- AGREGADO: Le decimos a Django dónde buscar tu carpeta "static" ---
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

JAZZMIN_SETTINGS = {
    "site_title": "ORBAT LatamSquad",
    "site_header": "75th RANGER RGT", 
    "site_brand": "MANDO CENTRAL",
    "site_logo": None,
    "welcome_sign": "Identifíquese, Operador.",
    "copyright": "LatamSquad Engineering",
    "search_model": "orbat.Miembro",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["orbat.Regimiento", "orbat.Compania", "orbat.Escuadra", "orbat.Miembro"],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "orbat.Regimiento": "fas fa-settings",
        "orbat.Compania": "fas fa-chess-rook",
        "orbat.Escuadra": "fas fa-chess-pawn",
        "orbat.Miembro": "fas fa-id-card-alt",
    },
    "user_avatar": None,
    # --- LA LÍNEA CLAVE ---
    "custom_css": "custom_admin.css", 
    "custom_js": None,

    
}

JAZZMIN_UI_TWEAKS = {
    "theme": "slate",
    "dark_mode_theme": "slate",
}